### PR TITLE
Performance improvement: don't scan entire log file on every chunk

### PR DESCRIPTION
**Pull request by Jimilian**
Hi,

I hope that I found a cheap way to make timestamper plugin a much faster (and decrease memory footprint). I tested this change in our Jenkins and it seems that everything are working as before, but faster.

@StevenGBrown, could you take a look into my PR?

### CODE REVIEW

**Comment by Jimilian** [comment]
@StevenGBrown, Hi! I know that sometimes github doesn't provide notification for first message in PR, so, I decided to write second :) I would appreciate any feedback about this change.

**Comment by StevenGBrown** [comment]
Hi! I'm afraid this won't do the trick, because the `ConsoleLogParser` needs the whole log file, and the text passed to `TimestampAnnotator` only contains the current line. If Jenkins starts annotating from somewhere in the middle of the log file, the wrong timestamps would be displayed. (For example, Jenkins only displays the last 150KB of a large log file to start with.)

I would be interested in seeing your timings though, and maybe we can something out! How big is your log file, how are you opening it in Jenkins, and how much time does that take before and after applying your commits?

**Comment by Jimilian** [comment]
Yes, you are right. Now it doesn't work in case of "tail of last 150KB".
With this "fix" it works twice faster for big log (50MB). But main idea was to decrease memory footprint on master. We have too much jobs and users in parallel that memory pressure means a lot of.
I will try to find better way to implement same logic.

**Comment by Jimilian** [comment]
@StevenGBrown, Oh, man, after several hours of debugging I understood that **exactly** I did :)
So, basically my initially thoughts were quite simple:
* Jenkins devs provided such signature to avoid full reading at all. 
* In current state (without this PR) timestamper reads entire file at least once (to calculate current line).
* If you have more than 100 users, it becomes too painful

That I think to implement ( if you agree ):
* In case `pos!=0`, I will read last `pos` bytes of file and calculate negative `offset` for line number. After that I will read last `offset` lines of timestamps. All this stuff should work without any issues if build is not in progress anymore (`build.isBuilding()` returns false)
* If build is still in progress I see two options: 
   * small lie (use same approach with last X bytes, but small race condition could happen if job posts a lot)
   * keep current behaviour

In worst case I can introduce a option on global level - `Don't print timestamp in "preview"`.

What do you think?

**Pull request closed without merging**
