### PR TITLE
Bump jcasc and baseline to fix bom

### PR DESCRIPTION
**Pull request by timja**
Picks up https://github.com/jenkinsci/bom/pull/315 and probably other PRs

Hoping to fix https://github.com/jenkinsci/bom/pull/290

cc @basil @jetersen @jglick

### CODE REVIEW

**Comment by timja** [comment]
missed your last release by 10 minutes 😢

**Comment by jglick** [comment]
:man_shrugging: Natural numbers are free.

**Review by basil — APPROVED** [review]

**Comment by jetersen** [comment]
Would appreciate another release to fix jenkinsci/bom

**Comment by zbynek** [comment]
btw. is it just me or did the parent POM bump break `hpi:run` for Timestamper (NPE from https://github.com/jenkinsci/maven-hpi-plugin/pull/191)?

**Comment by timja** [comment]
@Vlatombe fyi ^^

**Comment by basil** [comment]
> Would appreciate another release to fix jenkinsci/bom

Sure thing. Let's get #76 merged first and then I'll cut a release.

**Comment by timja** [comment]
hpi:run should be fixed in 4.12 of parent Pom :)

**Comment by basil** [comment]
Released in [1.11.7](https://github.com/jenkinsci/timestamper-plugin/releases/tag/timestamper-1.11.7).

**Pull request merged**
