### PR TITLE
[JENKINS-71055] Avoid duplicate widget in the side panel of running Pipeline builds

### PR DESCRIPTION
**Pull request by mawinter69**
while a pipeline build is running, the timestamper widget is displayed twice. This change avoids this.

### Testing done

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Review by basil — COMMENTED** [review]
This seems like a workaround for a bug somewhere else. Why would we ever be trying to load the same widget twice to begin with?

**Comment by mawinter69** [comment]
It might have to do with the specific way pipeline is rendering the console output which leads to the MutationObserver fire twice before the timestamper widget is created.

**Review by basil — CHANGES_REQUESTED** [review]
My standard response for workarounds applies.

Please find the root cause and fix it rather than adding a workaround.

If, once the root cause is understood, the fix is unreasonably involved, then file a ticket explaining what should be done to implement the long-term fix. Then file a separate ticket for removing the workaround being introduced this PR, blocked on the first ticket. Then I will accept this PR.

**Comment by mawinter69** [comment]
Found the root cause.
On page load the mutation observer is called once with multiple records where more than one has a timestamp this I think is absolutely to be expected (at least for pipeline jobs). The foreach loop is not exited by the return statement. Replaced it with a regular for loop and the problem is gone.

**Review by basil — APPROVED** [review]
Thanks for the PR!

**Comment by basil** [comment]
Released in [1.27](https://github.com/jenkinsci/timestamper-plugin/releases/tag/timestamper-1.27).

**Pull request merged**
