### PR TITLE
Update plugin POM

### PR DESCRIPTION
**Pull request by basil**
Bumps the [plugin parent POM](https://github.com/jenkinsci/plugin-pom) from 3.25 to 3.48.

See [the changelog](https://github.com/jenkinsci/plugin-pom/blob/master/CHANGELOG.md) and the full diff in [the compare view](https://github.com/jenkinsci/plugin-pom/compare/plugin-3.25...plugin-3.48).

### CODE REVIEW

**Comment by darxriggs** [comment]
LGTM

**Comment by darxriggs** [comment]
@jglick can you have a look at this?

**Comment by darxriggs** [comment]
Can this be merged?

**Comment by basil** [comment]
@jglick Gentle ping. Let me know if you lack the time for (or interest in) looking at open PRs for this repository and are OK with me becoming a co-maintainer. If so, I'll file a PR in `repository-permissions-updater`. If not, no rush on this.

**Comment by jglick** [comment]
> OK with me becoming a co-maintainer

By all means!

**Pull request merged**
