### PR TITLE
Restore compatibility with old JCasC config

### PR DESCRIPTION
**Pull request by timja**
Tried upgrading today and got:

```
jenkins    | io.jenkins.plugins.casc.ConfiguratorException: Invalid configuration elements for type class jenkins.model.GlobalConfigurationCategory$Unclassified : timestamperConfig.
jenkins    | Available attributes : administrativeMonitorsConfiguration, ansiColorBuildWrapper, appInsightsGlobalConfig, artifactManager, azureKeyVault, bitbucketEndpointConfiguration, buildDiscarders, buildMonitorView, casCGlobalConfig, defaultFolderConfiguration, defaultView, envVarsFilter, fingerprints, gitHubConfiguration, gitHubPluginConfig, gitSCM, globalDefaultFlowDurabilityLevel, globalLibraries, httpRequestGlobalConfig, jacoco, jiraGlobalConfiguration, location, lockableResourcesManager, mailer, masterBuild, mavenModuleSet, metricsAccessKey, myView, nodeProperties, pipeline-model-docker, plugin, pollSCM, projectNamingStrategy, prometheusConfiguration, quietPeriod, resourceRoot, scmRetryCount, shell, simple-theme-plugin, slackNotifier, sonarGlobalConfiguration, themeManager, timestamper, usageStatistics, viewsTabBar
```

This allows old scripts to still work and the default config will be the new one

cc @basil

### CODE REVIEW

**Comment by basil** [comment]
@jetersen Is this the recommended way to handle such cases in CasC?

**Comment by timja** [comment]
See https://github.com/jenkinsci/configuration-as-code-plugin/issues/1260 where this happened with declarative pipeline

Support for multiple symbols added in:
https://github.com/jenkinsci/configuration-as-code-plugin/pull/1308

**Comment by timja** [comment]
any chance of a release @basil?

**Comment by basil** [comment]
Released in [1.11.5](https://github.com/jenkinsci/timestamper-plugin/releases/tag/timestamper-1.11.5).

**Comment by olivergondza** [comment]
Note: This fix requires configuration-as-code 1.37 (and thus jenkins 2.222).

**Comment by timja** [comment]
> Note: This fix requires configuration-as-code 1.37 (and thus jenkins 2.222).

👍, it will just ignore it otherwise

**Pull request merged**
