### PR TITLE
SimpleBuildWrapper

### PR DESCRIPTION
**Pull request by jglick**
[JENKINS-27207](https://issues.jenkins-ci.org/browse/JENKINS-27207)

Downstream of https://github.com/jenkinsci/jenkins/pull/1634 and https://github.com/jglick/workflow-plugin/pull/1.

@reviewbybees

### CODE REVIEW

**Comment by StevenGBrown** [comment]
Cool! LGTM once we make it depend on 1.608.

**Comment by tfennelly** [comment]
:+1:

**Comment by jglick** [comment]
@StevenGBrown?

**Comment by StevenGBrown** [comment]
Hadn't noticed that you finished this. Great. I'll look at doing a release in a few days.

**Comment by StevenGBrown** [comment]
Released with Timestamper 1.7.

**Pull request merged**
